
#define _ECS_TEST

#define SEQ_TIME_OUT									100
#define SEQ_TIME_DELAY									10

#define USE_MSG_INLINE_CTRL								WM_USER+15
#define MSG_READ_ADDRS									0
#define MSG_WRITE_ADDRS									1
			
#define DATABASE_PATH									"D:\\DATABASE\\SYSTEM"
#define MAX_STRING_LINE									30000
#define ADDRESS_TYPE_WORD_AREA1							0
#define ADDRESS_TYPE_WORD_AREA2							1
#define ADDRESS_TYPE_BIT_AREA1							2

#define MAX_RECIPE_CNT									999
#define MAX_TIMEOUT_CNT									20
#define	MAX_TRIGGER_CNT									20

#define PLC_DEVW_APD_DATA_CNT							1280
#define PLC_DEVW_ESP_EQUIPMENT_SPECIFIC_DATA_CNT		16
#define PLC_DEVW_RBD_RECIPE_BODY_CNT					992
#define PLC_DEVW_ESD_EQUIPMENT_SPECIFIC_DATA_CNT		16
#define PLC_DEVW_RP_RECIPE_PARAMETER_CNT				992

#define MAX_MAP_CNT										7
#define MAX_ITEM_CNT									4000
#define MAX_POSITION_CNT								2

#define MELSEC_STATUS_DISCONNECT						-1

#define STATUS_RUN										0
#define STATUS_IDLE										1
#define STATUS_DOWN										2

#define MELSEC_ALL_ADDRESS_READ							0
#define MELSEC_WORD_ADDRESS1_READ						1
#define MELSEC_WORD_ADDRESS2_READ						2
#define MELSEC_BIT_ADDRESS_READ							3

#define	MELSEC_CHANNEL_NO								151
#define MELSEC_STATION_NO								9
#define MELSEC_PLC_STATION								255

#define AREA_WORD_1_START_ITEM_NUM						0
#define AREA_WORD_2_START_ITEM_NUM						1404 + 254
#define AREA_BIT_1_START_ITEM_NUM						3437 + 254

#define MAX_RECIPE_CNT									999
#define RECIPE_SEARCH_CNT								15

#define GLASS_DATA_SIZE									48

#define DEVW_USD_TPD_REPORT_NUMBER						0//0x2000,
#define DEVW_USD_TPD_UPDATE_TIME						1//0x2001,
#define DEVW_USD_IONIZER_STATUS_0_15					2//0x2006, //WORD -> BIT
#define DEVW_USD_IONIZER_STATUS_16_31					3//0x2007, //WORD -> BIT
#define DEVW_USD_LOT_JUDGE_CODE							4//0x2008,
#define DEVW_USD_UNIT_DOWN_ALARM_CODE					5//0x2009,
#define DEVW_USD_REQUEST_HOST_RECIPE_NUMBER				6//0x200A,
#define DEVW_USD_CURRENT_EQUIPMENT_RECIPE_NUMBER		7//0x200B,
#define DEVW_USD_GLASS_COUNT_IN_UNIT					8//0x200C,
#define DEVW_USD_PUT_INTO_POSSIBLE_COUNT				9//0x200D,
#define DEVW_USD_LIGHT_ALARM_CODE						10//0x200E,
#define DEVW_USD_HEAVY_ALARM_CODE						11//0x200F,
#define DEVW_RGD_LOT_ID									12//0x2010, //8WORD
#define DEVW_RGD_PROCESSING_CODE						13//0x2018, //4WORD
#define DEVW_RGD_LOT_SPECIFIC_DATA						14//0x201C, //4WORD
#define DEVW_RGD_HOST_RECIPE_NUMBER						15//0x2020,
#define DEVW_RGD_GLASS_TYPE								16//0x2021,
#define DEVW_RGD_GLASS_CODE_LOT_SLOT					17//0x2022,
#define DEVW_RGD_GLASS_ID								18//0x2023, //8WORD
#define DEVW_RGD_GLASS_JUDGE							19//0x202B,
#define DEVW_RGD_GLASS_SPECIFIC_DATA					20//0x202C, //4WORD
#define DEVW_RGD_GLASS_ADD_DATA							21//0x2030, //6WORD
#define DEVW_RGD_PREVIOUS_UNIT_PROCESSING_DATA			22//0x2036, //4WORD
#define DEVW_RGD_GLASS_PROCESSING_DATA					23//0x203A, //3WORD
#define DEVW_RGD_GLASS_ROUTING_DATA						24//0x203D, //3WORD
#define DEVW_RP_REPORT_PARAMETER_CEID					25//0x2040,
#define DEVW_RP_REPORT_PARAMETER_V1						26//0x2041,
#define DEVW_RP_REPORT_PARAMETER_V2						27//0x2042,
#define DEVW_RP_REPORT_PARAMETER_V3						28//0x2043,
#define DEVW_RP_REPORT_PARAMETER_V4						29//0x2044,
#define DEVW_RP_REPORT_PARAMETER_V5						30//0x2045,
#define DEVW_RP_REPORT_PARAMETER_V6						31//0x2046,
#define DEVW_RP_REPORT_PARAMETER_V7						32//0x2047,
#define DEVW_RP_REPORT_PARAMETER_V8						33//0x2048,
#define DEVW_RP_REPORT_PARAMETER_V9						34//0x2049,
#define DEVW_RP_REPORT_PARAMETER_V10					35//0x204A,
#define DEVW_RP_REPORT_PARAMETER_V11					36//0x204B,
#define DEVW_RP_REPORT_PARAMETER_V12					37//0x204C,
#define DEVW_RP_REPORT_PARAMETER_V13					38//0x204D,
#define DEVW_RP_REPORT_PARAMETER_V14					39//0x204E,
#define DEVW_RP_REPORT_PARAMETER_V15					40//0x204F,
#define DEVW_GSD_GLASS_DATA_REQUEST_GLASS_ID			41//0x2070, //8WORD
#define DEVW_GSD_GLASS_DATA_REQUEST_GLASS_CODE			42//0x2078,
#define DEVW_GSD_GLASS_DATA_REQUEST_OPTION				43//0x2079,
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_1_15			44//0x2080, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_16_31			45//0x2081, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_32_47			46//0x2082, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_48_63			47//0x2083, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_64_79			48//0x2084, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_80_95			49//0x2085, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_96_111			50//0x2086, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_112_127		51//0x2087, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_128_143		52//0x2088, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_144_159		53//0x2089, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_160_175		54//0x208A, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_176_191		55//0x208B, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_192_207		56//0x208C, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_208_223		57//0x208D, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_224_239		58//0x208E, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_240_255		59//0x208F, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_256_271		60//0x2090, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_272_287		61//0x2091, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_288_303		62//0x2092, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_304_319		63//0x2093, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_320_335		64//0x2094, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_336_351		65//0x2095, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_352_367		66//0x2096, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_368_383		67//0x2097, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_384_399		68//0x2098, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_400_415		69//0x2099, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_416_431		70//0x209A, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_432_447		71//0x209B, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_448_463		72//0x209C, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_464_479		73//0x209D, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_480_495		74//0x209E, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_496_511		75//0x209F, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_512_527		76//0x20A0, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_528_543		77//0x20A1, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_544_559		78//0x20A2, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_560_575		79//0x20A3, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_576_591		80//0x20A4, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_592_607		81//0x20A5, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_608_623		82//0x20A6, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_624_639		83//0x20A7, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_640_655		84//0x20A8, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_656_671		85//0x20A9, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_672_687		86//0x20AA, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_688_703		87//0x20AB, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_704_719		88//0x20AC, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_720_735		89//0x20AD, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_736_751		90//0x20AE, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_752_767		91//0x20AF, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_768_783		92//0x20B0, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_784_799		93//0x20B1, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_800_815		94//0x20B2, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_816_831		95//0x20B3, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_832_847		96//0x20B4, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_848_863		97//0x20B5, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_864_879		98//0x20B6, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_880_895		99//0x20B7, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_896_911		100//0x20B8, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_912_927		101//0x20B9, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_928_943		102//0x20BA, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_944_959		103//0x20BB, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_960_975		104//0x20BC, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_976_991		105//0x20BD, //WORD -> BIT
#define DEVW_ERN_EQUIPMENT_RECIPE_NUMBER_992_999		106//0x20BE, //WORD -> BIT
#define DEVW_POG_POSITION_1_GLASS_CODE					107//0x20C0,
#define DEVW_POG_POSITION_2_GLASS_CODE					108//0x20C1,
#define DEVW_UIGD_LOT_ID								109//0x2110, //8WORD
#define DEVW_UIGD_PROCESSING_CODE						110//0x2118, //4WORD
#define DEVW_UIGD_LOT_SPECIFIC_DATA						111//0x211C, //4WORD
#define DEVW_UIGD_HOST_RECIPE_NUMBER					112//0x2120,
#define DEVW_UIGD_GLASS_TYPE							113//0x2121, //WORD -> BIT
#define DEVW_UIGD_GLASS_CODE_LOT_SLOT					114//0x2122, //WORD -> BIT
#define DEVW_UIGD_GLASS_ID								115//0x2123, //8WORD
#define DEVW_UIGD_GLASS_JUDGE							116//0x212B,
#define DEVW_UIGD_GLASS_SPECIFIC_DATA					117//0x212C, //4WORD //WORD -> BIT 0 Bit£º Destination code 20, 1 Bit£º Destination code 21, 2 Bit£º Sorting type 20, 3 Bit£º Sorting type 21, 4 Bit£º Sorting type 22, 5 Bit£º Sorting type 23, 6 Bit£º DICODE, 7 Bit£º Glass Order 20, 8 Bit£º Glass Order 21, 9 Bit£º Direction code(1 : Reverse), CELL Only, A Bit£º Glass turn information code 20(0 : 0o, 1 : 90o, 2 : 180o, 3 : -90o), B Bit£º Glass turn information code 21(0 : 0o, 1 : 90o, 2 : 180o, 3 : -90o), C Bit£º Reserve, D Bit£º Reserve,E Bit£º Reserve, F Bit£º Reserve
#define DEVW_UIGD_GLASS_ADD_DATA						118//0x2130, //6WORD //WORD -> BIT C Bit£º Routing no.1 Processing Complete ( CELL Rubbing Only), D Bit£º Routing no.2 Processing Complete ( CELL Rubbing Only), E Bit£º Routing no.3 Processing Complete ( CELL Rubbing Only), F Bit£º Routing no.4 Processing Complete ( CELL Rubbing Only)
#define DEVW_UIGD_PREVIOUS_UNIT_PROCESSING_DATA			119//0x2136, //4WORD //WORD -> BIT
#define DEVW_UIGD_GLASS_PROCESSING_DATA					120//0x213A, //3WORD //WORD -> BIT
#define DEVW_UIGD_GLASS_ROUTING_DATA					121//0x213D, //3WORD //WORD -> BIT
#define DEVW_TPD_DATA_V1								122//0x2200,
#define DEVW_TPD_REPORT_NUMBER							123 + 254//0x22FF,
#define DEVW_APD_DATA_V1								124 + 254//0x2300, //V1280
#define DEVW_RBR_RECIPE_REPORT_CEID						1404 + 254//0x14000,
#define DEVW_RBR_RECIPE_NUMBER							1405 + 254//0x14001,
#define DEVW_RBR_RECIPE_CONFIRM_ACK						1406 + 254//0x14002,
#define DEVW_RBR_RECIPE_LEVEL							1407 + 254//0x14003,
#define DEVW_RBR_RECIPE_TYPE							1408 + 254//0x14004,
#define DEVW_RBR_RECIPE_VERSION							1409 + 254//0x14005, //3WORD
#define DEVW_ESP_EQUIPMENT_SPECIFIC_DATA_V1				1410 + 254//0x14010, //V16
#define DEVW_RBD_RECIPE_BODY_V1							1426 + 254//0x14020, //V992
#define DEVW_RCR_REQUEST_CONFIRM_CEID					2418 + 254//0x14400,
#define DEVW_RCR_REQUEST_CONFIRM_ACK					2419 + 254//0x14401,
#define DEVW_RCR_RECIPE_REPORT_CEID						2420 + 254//0x14404,
#define DEVW_RCR_RECIPE_REPORT_CEID_ORDER				2421 + 254//0x14405,
#define DEVW_RCR_RECIPE_TOTAL_COUNT						2422 + 254//0x14406,
#define DEVW_RCR_RECIPE_REPORT_COUNT					2423 + 254//0x14407,
#define DEVW_RCR_RECIPE_COMMAND							2424 + 254//0x14408,
#define DEVW_RCR_RECIPE_NUMBER							2425 + 254//0x14409,
#define DEVW_RCR_RECIPE_LEVEL							2426 + 254//0x1440A,
#define DEVW_RCR_RECIPE_TYPE							2427 + 254//0x1440B,
#define DEVW_RCR_RECIPE_VERSION							2428 + 254//0x1440C, //3WORD
#define DEVW_ESD_EQUIPMENT_SPECIFIC_DATA_V1				2429 + 254//0x14410, //V16
#define DEVW_RP_RECIPE_PARAMETER_V1						2445 + 254//0x14420, //V992
#define DEVB_ONLINE										3437 + 254//0x1000,
#define DEVB_AUTO_MODE									3438 + 254//0x1005,
#define DEVB_OPERATION_CYCLE_STOP						3439 + 254//0x1007,
#define DEVB_RUN										3440 + 254//0x1008,
#define DEVB_IDLE										3441 + 254//0x1009,
#define DEVB_DOWN										3442 + 254//0x100A,
#define DEVB_GLASS_IN_PROCESSING						3443 + 254//0x100B,
#define DEVB_GLASS_EXIST_IN_UNIT						3444 + 254//0x100C,
#define DEVB_PREVIOUS_TRANSFER_ENABLE					3445 + 254//0x100D,
#define DEVB_LIGHT_ALARM_REPORT							3446 + 254//0x100E,
#define DEVB_HEAVY_ALARM_REPORT							3447 + 254//0x100F,
#define DEVB_MODE_AUTO									3448 + 254//0x1010,
#define DEVB_MODE_MANUAL								3449+ 254//0x1011,
#define DEVB_GLASS_APD_DATA_REPORT						3450+ 254//0x1021,
#define DEVB_SCRAP_GLASS_DATA_REPORT					3451+ 254//0x1022,
#define DEVB_LOST_GLASS_DATA_REQUEST					3452+ 254//0x1023,
#define DEVB_GLASS_DATA_CHANGE_REPORT					3453+ 254//0x1024,
#define DEVB_RECIPE_BODY_DATA_REPORT					3454+ 254//0x1028,
#define DEVB_EQIPMENT_RECIPE_REQUEST					3455+ 254//0x102A,
#define DEVB_EQP_RECIPE_LIST_CHANGE						3456+ 254//0x102B,
#define DEVB_RECIPE_VARIOUS_REQUEST_CONFIRM				3457+ 254//0x102D,
#define DEVB_RECIPE_VARIOUS_DATA_REPORT					3458+ 254//0x102E,
#define DEVB_POSITION1_GLASS_EXIST						3459+ 254//0x10C0,
#define DEVB_POSITION2_GLASS_EXIST						3460+ 254//0x10C1,
#define DEVB_LOAD_ENABLE								3461+ 254//0x1100,
#define DEVB_LOAD_GLASS_DATA_REQUEST					3462+ 254//0x1101,
#define DEVB_LOAD_NORMAL_STATUS							3463+ 254//0x1104,
#define DEVB_LOAD_REQUEST								3464+ 254//0x1105,
#define DEVB_LOAD_COMPLETE_CONFIRM						3465+ 254//0x1106,
#define DEVB_LOAD_WAIT_OPTION							3466+ 254//0x110B,
#define DEVB_UNLOAD_ENABLE								3467+ 254//0x1110,
#define DEVB_UNLOAD_GLASS_DATA_REQUEST					3468+ 254//0x1111,
#define DEVB_UNLOAD_NORMAL_STATUS						3469+ 254//0x1114,
#define DEVB_UNLOAD_REQUEST								3470+ 254//0x1115,
#define DEVB_UNLOAD_COMPLETE_CONFIRM					3471+ 254//0x1116,
#define DEVB_UNLOAD_WAIT_OPTION							3472+ 254//0x111B,

////////////////////////////////////////////////////////////////////////////////////
//robot bit address
#define ROBOT_B_ADDRESS_UNLOADER_NORMAL_STATUS			0x0804
#define ROBOT_B_ADDRESS_UNLOADER_NONINTERFERENCE		0x0800
#define ROBOT_B_ADDRESS_UNLOADER_ROBOT_BUSY				0x0802
#define ROBOT_B_ADDRESS_UNLOADER_COMPLETE				0x0803
#define ROBOT_B_ADDRESS_LOADER_NORMAL_STATUS			0x0814
#define ROBOT_B_ADDRESS_LOADER_NONINTERFERENCE			0x0810
#define ROBOT_B_ADDRESS_LOADER_GLASS_DATA_REPORT		0x0811
#define ROBOT_B_ADDRESS_LOADER_ROBOT_BUSY				0x0812
#define ROBOT_B_ADDRESS_LOADER_COMPLETE					0x0813

//robot word address
#define ROBOT_W_ADDRESS_LOADER_GLASS_DATA				0x1010//48WORD
////////////////////////////////////////////////////////////////////////////////////


////////////////////////////////////////////////////////////////////////////////////
//ecs bit address
#define ECS_B_ADDRESS_TIME_DATA_SEND					0x0010
#define ECS_B_ADDRESS_ECS_START							0x0011
#define ECS_B_ADDRESS_ECS_OPERATION_NODE_CHANGE			0x0012
#define ECS_B_ADDRESS_LOT_END_SEND						0x0013
#define ECS_B_ADDRESS_GLASS_DATA_REQUEST_ACK_OK			0x0020
#define ECS_B_ADDRESS_GLASS_DATA_REQUEST_ACK_NG			0x0021
#define ECS_B_ADDRESS_RECIPE_BODY_DATA_REQUEST			0x0074
#define ECS_B_ADDRESS_EQUIPMENT_RECIPE_REPORT			0x00A4
#define ECS_B_ADDRESS_GLASS_DATA_REPORT					0x00D4
#define ECS_B_ADDRESS_RECIPE_VARIOUS_DATA_REQUEST		0x0104
#define ECS_B_ADDRESS_RECIPE_VARIOUS_DATA_CONFIRM		0x0134

//ecs word address
#define ECS_W_ADDRESS_TIME_DATA							0x0000//6WORD
#define ECS_W_ADDRESS_LOT_END_LOT_ID					0x0006//8WORD
#define ECS_W_ADDRESS_LOT_END_NUMBER					0x000E
#define ECS_W_ADDRESS_RBD_REQUEST_RECIPE_NUMBER			0x0074
#define ECS_W_ADDRESS_EQUIPMENT_RECIPE_NUMBER			0x00A4
#define ECS_W_ADDRESS_GLASS_DATA						0x00D0//48WORD
#define ECS_W_ADDRESS_RVD_REQUEST_CEID					0x10000
#define ECS_W_ADDRESS_RVD_REQUEST_RECIPE_COMMAND		0x10001
#define ECS_W_ADDRESS_RVD_REQUEST_RECIPE_NUMBER			0x10002
#define ECS_W_ADDRESS_RVD_REQUEST_RECIPE_LEVEL			0x10003
#define ECS_W_ADDRESS_RVD_REQUEST_RECIPE_TYPE			0x10004
#define ECS_W_ADDRESS_RVD_REQUEST_RECIPE_VERSION		0x10005//3WORD
#define ECS_W_ADDRESS_RVD_REQUEST_UNIT_NUMBER			0x10008
#define ECS_W_ADDRESS_RVD_EQUIPMENT_SPECIFIC_DATA		0x10010//16WORD
#define ECS_W_ADDRESS_RVD_RECIPE_PARAMETER				0x10020//992WORD
#define ECS_W_ADDRESS_RVD_VARIOUS_DATA_END				0x103FF
////////////////////////////////////////////////////////////////////////////////////

//RECIPE BODY
////////////////////////////////////////////////////////
//DATA REPORT CEID
#define RECIPE_BODY_DATA_REPORT					3

//RECIPE REQUESTCONFIRM ACK
#define RECIPE_CONFIRM_OK						0
#define INVALID_RECIPE_NUMBER					1
#define RECIPE_CONFIRM_NOT_ACCEPT				2

//RECIPE LEVEL
#define LEVEL_2_RECIPE_EQUIPMENT_RECIPE			2
#define LEVEL_3_RECIPE_EQUIPMENT_SUB_RECIPE		3

//RECIPE TYPE
#define RECIPE_TYPE_MACHIN_RECIPE				"M"
#define RECIPE_TYPE_UNIT_RECIPE					"U"
#define RECIPE_TYPE_SPECIAL_RECIPE_1			"1"
#define RECIPE_TYPE_SPECIAL_RECIPE_2			"2"
#define RECIPE_TYPE_SPECIAL_RECIPE_3			"3"
#define RECIPE_TYPE_SPECIAL_RECIPE_4			"4"
#define RECIPE_TYPE_SPECIAL_RECIPE_5			"5"
#define RECIPE_TYPE_SPECIAL_RECIPE_6			"6"
#define RECIPE_TYPE_SPECIAL_RECIPE_7			"7"
#define RECIPE_TYPE_SPECIAL_RECIPE_8			"8"
#define RECIPE_TYPE_SPECIAL_RECIPE_9			"9"
////////////////////////////////////////////////////////

//RECIPE VARIOUS ACK
////////////////////////////////////////////////////////
//CONFIRM CEID
#define RECIPE_VARIOUS_ACK_CONFIRM_CEID_RECIPE_LIST										1
#define RECIPE_VARIOUS_ACK_CONFIRM_CEID_LOWER_RECIPE_LIST								2
#define RECIPE_VARIOUS_ACK_CONFIRM_CEID_RECIPE_PARAMETER								3
#define RECIPE_VARIOUS_ACK_CONFIRM_CEID_RECIPE_COMMAND									5
#define RECIPE_VARIOUS_ACK_CONFIRM_CEID_EQP_CONSTANT_RECIPE_PARAMETER_HOST_ONLINE		6
#define RECIPE_VARIOUS_ACK_CONFIRM_CEID_EQP_CONSTANT_RECIPE_PARAMETER_HOST_REQUEST		7
#define RECIPE_VARIOUS_ACK_CONFIRM_CEID_EQP_CONSTANT_RECIPE_COMMAND						9

//CONFIRM ACK
#define RECIPE_VARIOUS_ACK_CONFIRM_ACK_ACCEPTED											0
#define RECIPE_VARIOUS_ACK_CONFIRM_ACK_PERMISSION_NOT_GRANTED							1
#define RECIPE_VARIOUS_ACK_CONFIRM_ACK_RECIPE_NUMBER_USING								2
#define RECIPE_VARIOUS_ACK_CONFIRM_ACK_EQUIPMENT_NOT_RESPONDING							3
#define RECIPE_VARIOUS_ACK_CONFIRM_ACK_VERSION_NOT_FOUND								4
#define RECIPE_VARIOUS_ACK_CONFIRM_ACK_RECIPE_NUMBEER_NOT_FOUND							5
#define RECIPE_VARIOUS_ACK_CONFIRM_ACK_LENGTH_ERROR										6
#define RECIPE_VARIOUS_ACK_CONFIRM_ACK_PARAMETER_RANGE_ERROR							7
#define RECIPE_VARIOUS_ACK_CONFIRM_ACK_SAME_NAME_OF_RECIPES_EXIST						8
////////////////////////////////////////////////////////

//RECIPE VAIOUS DATA REPORT
////////////////////////////////////////////////////////
#define RECIPE_VARIOUS_REPORT_RECIPE_CEID_RECIPE_LIST									1
#define RECIPE_VARIOUS_REPORT_RECIPE_CEID_OWER_RECIPE_LIST								2
#define RECIPE_VARIOUS_REPORT_RECIPE_CEID_RECIPE_PARAMETER								3
#define RECIPE_VARIOUS_REPORT_RECIPE_CEID_RECIPE_CHANGE_REPORT							5
#define RECIPE_VARIOUS_REPORT_RECIPE_CEID_EQP_CONSTANT_RECIPE_PARAMETER_HOST_ONLINE		6
#define RECIPE_VARIOUS_REPORT_RECIPE_CEID_EQP_CONSTANT_RECIPE_PARAMETER_HOST_REQUEST	7
#define RECIPE_VARIOUS_REPORT_RECIPE_CEID_EQP_CONSTANT_RECIPE_CHANGE_REPORT				9

#define RECIPE_VARIOUS_REPORT_RECIPE_CEID_ORDER_FIRST_REPORT_CEID						0
#define RECIPE_VARIOUS_REPORT_RECIPE_CEID_ORDER_CEID_EXCEPT_THE_FIRST_AND_THE_LAST		1
#define RECIPE_VARIOUS_REPORT_RECIPE_CEID_ORDER_LAST_REPORT_CEID						2

#define RECIPE_VARIOUS_REPORT_RECIPE_COMMAND_BUILT										1
#define RECIPE_VARIOUS_REPORT_RECIPE_COMMAND_CHANGE										2
#define RECIPE_VARIOUS_REPORT_RECIPE_COMMAND_DELETE										3
#define RECIPE_VARIOUS_REPORT_RECIPE_COMMAND_RENAME										4
////////////////////////////////////////////////////////

#define INIT_SEQ_BIT																	3
#define LOAD_ONLY																		0
#define UNLOAD_ONLY																		1
#define EXCHANGE																		2
#define DOWN_ALARM																		3


//timer define
#define TIMER_INTERLOCK_LOAD_ONLY														10
#define TIMER_INTERLOCK_UNLOAD_ONLY														20
#define TIMER_INTERLOCK_EXCHANGE														30

#define TIMER_LOADER_ROBOT_BUSY_ON_AND_EQP_LOADER_NORMAL_OFF_CHECK						100
#define TIMER_UNLOADER_ROBOT_BUSY_ON_AND_EQP_UNLOADER_NORMAL_OFF_CHECK					110
#define TIMER_LOADER_ROBOT_BUSY_ON_AND_ROBOT_LOADER_NORMAL_OFF_CHECK					120
#define TIMER_UNLOADER_ROBOT_BUSY_ON_AND_ROBOT_UNLOADER_NORMAL_OFF_CHECK				130
#define TIMER_LOADER_ENABLE_CHECK														140
#define TIMER_UNLOADER_ENABLE_CHECK														150
#define TIMER_ECS_START_STATUE_CHECK													160
#define TIMER_RECIPE_BODY_DATA_REQUEST													300
#define TIMER_RECIPE_BODY_DATA_REPORT													310
#define TIMER_ECS_TIME_DATA_GET															320
#define TIMER_RECIPE_VARIOUS_DATA_REQUEST												330
#define TIMER_SCRAP_GLASS_DATA_REPORT													340
#define TIMER_LOST_GLASS_DATA_REPORT													350
#define TIMER_CHANGE_GLASS_DATA_REPORT													360
#define TIMER_APD_DATA_REPORT															370
#define TIMER_TPD_DATA_REPORT															380


//TRIGGER
#define TRIGGER_RECIPE_NUMBER_LIST_CHANGE												0//1SEC
#define TRIGGER_SCRAP_GLASS_DATA_REPORT													1//1SEC
#define TRIGGER_GLASS_DATA_CHANGE_REPORT												2//1SEC
#define TRIGGER_GLASS_APD_DATA_REPORT													3//1SEC
#define TRIGGER_LIGHT_ALARM																4//1SEC
#define TRIGGER_HEAVY_ALARM																5//1SEC
#define TRIGGER_SEQUENCE_DELAY															6//1sec
#define TRIGGER_TPD_DATA_DELAY															7//0.5sec

//TIMEOUT
#define TIMEOUT_RECIPE_BODY_DATA_REQUEST												0//3SEC LIGHT ALARM
#define TIMEOUT_EQP_RECIPE_REQUEST_CONFIRM												1//3SEC LIGHT ALARM
#define TIMEOUT_RECIPE_VARIOUS_DATA_REQUEST												2//10SEC LIGHT ALARM
#define TIMEOUT_RECIPE_VARIOUS_DATA_REPORT												3//10SEC LIGHT ALARM
#define TIMEOUT_LOST_GLASS_DATA_REQUEST													4//3SEC LIGHT ALARM
#define TIMEOUT_GLASS_DATA_REQUEST														5//15sec
#define TIMEOUT_SEQUENCE																6//10sec
#define	TIMEOUT_ROBOTBUSY																7//180sec


#define RMS_RECIPE_LIST_FIRST_REPORT													0
#define RMS_RECIPE_LIST_EXCEPT_REPORT													1
#define RMS_RECIPE_LIST_LAST_REPORT														2

#define LOST_GLASS_DATA_OPTION_ID														0
#define LOST_GLASS_DATA_OPTION_CODE														1

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//interlock Alarm Level
#define INTERLOCK_EROR_LIGHT_ALARM																		0
#define INTERLOCK_EROR_HEAVY_ALARM																		1


//interlock Alarm code
#define INTERLOCK_ERROR_RECIPE_NUM_MISMATCH																0				//L	240	
#define INTERLOCK_ERROR_LOT_ID_NULL																		1				//L	241
#define INTERLOCK_ERROR_GLASS_ID_NULL																	2				//L	242
#define INTERLOCK_ERROR_RECIPE_BODY_DATA_REQUEST_OFF_TIMEOUT											3				//L	243		e
#define INTERLOCK_ERROR_EQP_RECIPE_REQUEST_CONFIRM_ON_TIMEOUT											4				//L	244		e
#define INTERLOCK_ERROR_RECIPE_LIST_REQUEST_OFF_TIMEOUT													5				//L	245		e
#define INTERLOCK_ERROR_RECIPE_LIST_REQUEST_CONFIRM_ON_TIMEOUT											6				//L	246		e
#define INTERLOCK_ERROR_RECIPE_PARAMETER_REQUEST_OFF_TIMEOUT											7				//L	247		e
#define INTERLOCK_ERROR_RECIPE_PARAMETER_REQUEST_CONFIRM_ON_TIMEOUT										8				//L	248		e
#define INTERLOCK_ERROR_RECIPE_COMMAND_BUILT_REQUEST_OFF_TIMEOUT										9				//L	249		e
#define INTERLOCK_ERROR_RECIPE_COMMAND_CHANGE_REQUEST_OFF_TIMEOUT										10				//L	250		e
#define INTERLOCK_ERROR_RECIPE_COMMAND_DELETE_REQUEST_OFF_TIMEOUT										11				//L	251		e
#define INTERLOCK_ERROR_RECIPE_COMMAND_RENAME_REQUEST_OFF_TIMEOUT										12				//L	252		e
#define INTERLOCK_ERROR_RECIPE_CHANGE_REPORT_CONFIRM_ON_TIMEOUT											13				//L	253		e
#define INTERLOCK_ERROR_EQP_CONSTANT_RECIPE_PARAMETER_REQUEST_OFF_TIMEOUT								14				//L	254		e
#define INTERLOCK_ERROR_EQP_CONSTANT_RECIPE_PARAMETER_CONFIRM_ON_TIMEOUT								15				//L	255		e
#define INTERLOCK_ERROR_LAST_GLASS_DATA_REQUEST_ON_TIMEOUT												16				//L	256		e
#define INTERLOCK_ERROR_LOADER_NONINTERFERENCET_ON_TIMEOUT												17				//H	257		r
#define INTERLOCK_ERROR_LOADER_NONINTERFERENCET_OFF_TIMEOUT												18				//H	258		r
#define INTERLOCK_ERROR_EQP_LOADER_NORMAL_STATUS_OFF													19				//H	259		m
#define INTERLOCK_ERROR_ROBOT_LOADER_NORMAL_STATUS_OFF													20				//H	260		r
#define INTERLOCK_ERROR_EQP_LOADER_ENABLE_OFF															21				//H	261		m
#define INTERLOCK_ERROR_EQP_LOADER_COMPLETE_TIMEOUT														22				//H	262		m
#define INTERLOCK_ERROR_UNLOADER_NONINTERFERENCET_ON_TIMEOUT											23				//H	263		r
#define INTERLOCK_ERROR_UNLOADER_NONINTERFERENCET_OFF_TIMEOUT											24				//H	264		r
#define INTERLOCK_ERROR_EQP_UNLOADER_NORMAL_STATUS_OFF													25				//H	265		m
#define INTERLOCK_ERROR_ROBOT_UNLOADER_NORMAL_STATUS_OFF												26				//H	266		r
#define INTERLOCK_ERROR_EQP_UNLOADER_ENABLE_OFF															27				//H	267		m
#define INTERLOCK_ERROR_EQP_UNLOADER_COMPLETE_TIMEOUT													28				//H	268		m
#define INTERLOCK_ERROR_UNLOADER_ROBOT_BUSY_ON_TIMEOUT													29				//H	269		r
#define INTERLOCK_ERROR_UNLOADER_ROBOT_COMPLETE_OFF_TIMEOUT												30				//H	270		r
#define INTERLOCK_ERROR_LOADER_ROBOT_BUSY_OFF_TIMEOUT													31				//H	271		r
#define INTERLOCK_ERROR_LOADER_ROBOT_COMPLETE_OFF_TIMEOUT												32				//H	272		r
#define INTERLOCK_ERROR_UNLOADER_ROBOT_BUSY_OFF_TIMEOUT													33				//H	273		r
#define INTERLOCK_ERROR_UNLOADER_ROBOT_COMPLETE_ON_TIMEOUT												34				//H	274		r
#define INTERLOCK_ERROR_LOADER_ROBOT_BUSY_ON_TIMEOUT													35				//H	275		r
#define INTERLOCK_ERROR_LOADER_ROBOT_COMPLETE_ON_TIMEOUT												36				//H	276		r

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//
//#define  INTERLOCK_ERROR_UNLOADER_ROBOT_BUSY_ON_TIMEOUT													0x0000				//H
//#define  INTERLOCK_ERROR_UNLOADER_ROBOT_COMPLETE_OFF_TIMEOUT											0x0001				//H
//#define  INTERLOCK_ERROR_LOADER_ROBOT_BUSY_OFF_TIME_OVEROUT												0x0002				//H
//#define  INTERLOCK_ERROR_LOADER_ROBOT_COMPLETE_OFF_TIMEOUT												0x0003				//H
//#define  INTERLOCK_ERROR_RECIPE_BODY_DATA_REQUEST_OFF_TIMEOUT											0x0004				//L
//#define  INTERLOCK_ERROR_EQP_RECIPE_REQUEST_CONFIRM_ON_TIMEOUT											0x0005				//L
//#define  INTERLOCK_ERROR_RECIPE_LIST_REQUEST_OFF_TIMEOUT												0x0006				//L
//#define  INTERLOCK_ERROR_RECIPE_LIST_REQUEST_CONFIRM_ON_TIMEOUT											0x0007				//L
//#define  INTERLOCK_ERROR_RECIPE_PARAMETER_REQUEST_OFF_TIMEOUT											0x0008				//L
//#define  INTERLOCK_ERROR_RECIPE_PARAMETER_REQUEST_CONFIRM_ON_TIMEOUT									0x0009				//L
//#define  INTERLOCK_ERROR_RECIPE_COMMAND_BUILT_REQUEST_OFF_TIMEOUT										0x000A				//L
//#define  INTERLOCK_ERROR_RECIPE_COMMAND_CHANGE_REQUEST_OFF_TIMEOUT										0x000B				//L
//#define  INTERLOCK_ERROR_RECIPE_COMMAND_DELETE_REQUEST_OFF_TIMEOUT										0x000C				//L
//#define  INTERLOCK_ERROR_RECIPE_COMMAND_RENAME_REQUEST_OFF_TIMEOUT										0x000D				//L
//#define  INTERLOCK_ERROR_RECIPE_CHANGE_REPORT_CONFIRM_ON_TIMEOUT										0x000E				//L
//#define  INTERLOCK_ERROR_EQP_CONSTANT_RECIPE_PARAMETER_REQUEST_OFF_TIMEOUT								0x000F				//L
//#define  INTERLOCK_ERROR_EQP_CONSTANT_RECIPE_PARAMETER_CONFIRM_ON_TIMEOUT								0x0010				//L
//#define  INTERLOCK_ERROR_LAST_GLASS_DATA_REQUEST_ON_TIMEOUT												0x0011				//L
//#define  INTERLOCK_ERROR_GLASS_DATA_NULL																0x0012				//H
//#define  INTERLOCK_ERROR_LOADER_NONINTERFERENCET_ON_TIMEOUT												0x0013				//H
//#define  INTERLOCK_ERROR_LOADER_NONINTERFERENCET_OFF_TIMEOUT											0x0014				//H
//#define  INTERLOCK_ERROR_EQP_LOADER_NORMAL_STATUS_OFF													0x0015				//H
//#define  INTERLOCK_ERROR_ROBOT_LOADER_NORMAL_STATUS_OFF													0x0016				//H
//#define  INTERLOCK_ERROR_EQP_LOADER_ENABLE_OFF															0x0017				//H
//#define  INTERLOCK_ERROR_EQP_LOADER_COMPLETE_TIMEOUT													0x0018				//H
//#define  INTERLOCK_ERROR_UNLOADER_NONINTERFERENCET_ON_TIMEOUT											0x0019				//H
//#define  INTERLOCK_ERROR_UNLOADER_NONINTERFERENCET_OFF_TIMEOUT											0x001A				//H
//#define  INTERLOCK_ERROR_EQP_UNLOADER_NORMAL_STATUS_OFF													0x001B				//H
//#define  INTERLOCK_ERROR_ROBOT_UNLOADERNORMAL_STATUS_OFF												0x001C				//H
//#define  INTERLOCK_ERROR_EQP_UNLOADER_ENABLE_OFF														0x001D				//H
//#define  INTERLOCK_ERROR_EQP_UNLOADER_COMPLETE_TIMEOUT													0x001E				//H
//#define  INTERLOCK_ERROR_UNLOADER_ROBOT_BUSY_OFF_TIMEOUT												0x001F				//H
//#define  INTERLOCK_ERROR_UNLOADER_ROBOT_COMPLETE_ON_TIMEOUT												0x0020				//H
//#define  INTERLOCK_ERROR_LOADER_ROBOT_BUSY_ON_TIME_OVEROUT												0x0021				//H
//#define  INTERLOCK_ERROR_LOADER_ROBOT_COMPLETE_ON_TIMEOUT												0x0022				//H
